version: '3.8'

services:
  backend:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ../frontend  
      dockerfile: Dockerfile
    ports:
      - "3000:80"  
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080  
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: db-container
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=animalshelter
    ports:
      - "3306:3306" 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
