version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    # Si necesitas una base de datos u otros servicios, añádelos aquí
    # volumes:
    #   - ./data:/data
