version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: db_animalshelter
      MYSQL_ROOT_PASSWORD: my_secure_password  # Cambia esto a una contraseña segura
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db_animalshelter
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: my_secure_password  # Asegúrate de que coincida con MYSQL_ROOT_PASSWORD
    depends_on:
      - db

volumes:
  db_data:
